### ISSUE TITLE
can't load package: package github.com/cpmech/gosl: no Go files in /home/unix/go/src/github.com/cpmech/gosl

### ISSUE THREAD

**Issue by ouening** [cpmech/gosl#56]
Hi, when I try to install this package using command `go get github.com/cpmech/gosl`, I got error as title said. I'm a new guy to golang, how can I solve it?

**Comment by cpmech** [comment]
Hi there,

We can only `go get` "real" packages, for example `go get github.com/cpmech/gosl/io` (note `io` at the end).

The readme file was incorrect but now it mentions `git clone` instead of `go get` as follows:

```
git clone https://github.com/cpmech/gosl.git
cd gosl
./all.bash
```

Note that the above procedure (**not** using Docker) requires the installation of Go and some additional libraries (as explained in the Readme file).

Cheers.
Dorival
